[build]
  publish = "."
  command = "echo 'Static site â€“ no build required'"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_DISABLE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
